version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_recovery_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
